spring:
  application:
    name: outdry-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/outdry_db
    username: akorovai
    password: akorovai
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 5000
      pool-name: HikariCP
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED
      initialization-fail-timeout: 1
      validation-timeout: 5000
      keepalive-time: 0

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true
        connection:
          provider_disables_autocommit: false
    open-in-view: false

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000, expireAfterWrite=10m, recordStats
    cache-names: users, products, orders

  #  mail:
  #    host: smtp.gmail.com
  #    port: 587
  #    username: your_email@gmail.com
  #    password: your_email_password
  #    properties:
  #      mail:
  #        smtp:
  #          auth: true
  #          starttls:
  #            enable: true

  actuator:
    endpoints:
      web:
        exposure:
          include: health, metrics, prometheus
    metrics:
      export:
        prometheus:
          enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    org.springframework.cache: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 80

# Database-specific properties
database:
  driver: org.postgresql.Driver
  version: 17.2
  autocommit: true
  isolation-level: READ_COMMITTED
  connection-pool:
    minimum-size: 5
    maximum-size: 20